### ISSUE TITLE
Marca un Error

### ISSUE THREAD

**Issue by carAlcocer** [configuroweb/manejadordearchivos#1]
Estimado muy buena tarde:

Felicidades por un excelente trabajo, te comento que lo estoy probando en un ambiente de hosting con mysql! El código como tal funciona al crear nuevas carpetas y alojar archivos, La tabla no muestra nada y al deshabilitar los errores me sale lo siguiente:

Notice: Undefined index: file

El cual hace referencia a diferentes líneas donde se encuentra el siguiente código:
$tmp = get_absolute_path($tmp_dir . '/' .$_REQUEST['file']);

Notice: Undefined index: do
if($_GET['do'] == 'list')

Gracias, quedo al pendiente de tus comentarios. Saludos

**Comment by configuroweb** [comment]
Si van pasando, versiones de PHP y algunos patrones, librerías van dejando de funcionar adecuadamente, tengo otros software, ya mejorados al manejador de archivos, tengo uno totalmente gratuito con conexiones a base de datos en sqlite, y otro de pago, más robuso, te recomiendo visites mi página web:

https://configuroweb.com
